/*
 * Implementing the Schedulable Interface
 * Execute the ExampleBatch class using the Schedulable interface.
 */
public with sharing class ExampleSchedule {
	/*
	 * Update/Uncomment the template code to create a method
	 * Method to execute the schedule job job
	 * Code to execute the batch job should not need to change other than uncommenting the code
	 */
	//[public | private ] [static] data_type execute (input parameters) {
	//NextStepBatch batch = new NextStepBatch();
	//Database.executeBatch(batch);
	//}
}
