/*
 * Update/Uncomment the template code to create a method
 * Create a future method that updates all account and opportunities description to 'Meeting in the future'
 */

public with sharing class ExampleFuture {
	@future
	public static void updateDescription() {
		// Define the new value for the description field.

		// Query all Account records and their related Opportunities.

		// Loop through each Account in our map.
			// Update the description field for the Account.

		// Commit the changes for the Accounts to the database.
	}
}
