name: Run Code Scan and Unit Tests

# Definition when the workflow should run
on:
    # The workflow will run whenever an event happens on a pull request
    workflow_call:

# Permissions needed for uploading SARIF results
permissions:
    security-events: write
    actions: read
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install sfdx with npm
              run: |
                  npm i @salesforce/cli --global

            - name: Install Code Analyzer plugin
              run: |
                  sf plugins install code-analyzer

            - name: Scan code with Code Analyzer v5
              run: |
                  sf code-analyzer run --rule-selector Recommended --workspace force-app/ --output-file apexScanResults.sarif

            - name: Authenticate Dev Hub
              run: |
                  echo ${{ secrets.CCA_AUTH_URL }} > sfdx_auth
                  sfdx force:auth:sfdxurl:store -f sfdx_auth -d -a DevHub

            - name: Display Dev Hub Limits
              run: |
                  sfdx force:limits:api:display -u DevHub

            - name: Create Scratch Org
              id: create-scratch-org
              run: |
                  sf org create scratch --duration-days 1 --alias CI_ScratchOrg --definition-file config/project-scratch-def.json

            - name: Deploy classes to org
              run: |
                  sf project deploy start --target-org CI_ScratchOrg

            - name: Run Apex Unit Tests
              run: |
                  sf apex test run -r human -c --wait 10 --target-org CI_ScratchOrg

            - name: Upload SARIF file
              if: always()
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: apexScanResults.sarif

            - name: Delete Scratch Org
              if: always()
              run: |
                  sf org delete scratch --target-org CI_ScratchOrg --no-prompt
